server.port=8081
spring.application.name=wellness-resource-service

# Postgres container service name
spring.datasource.url=jdbc:postgresql://postgres:5432/wellness
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# Redis container service name
spring.cache.type=redis
spring.data.redis.host=redis
spring.data.redis.port=6379

management.endpoints.web.exposure.include=health,info

# =========================
# Kafka Consumer (Docker)
# =========================
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=wellness-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=ca.gbc.comp3095.event.kafka
spring.kafka.consumer.properties.spring.json.value.default.type=ca.gbc.comp3095.event.kafka.EventCreatedMessage

